In [1]:
import numpy as np

In [24]:
# 1D Array using NumPy
a = np.array([2,3,4,5])
print(a)

[2 3 4 5]


In [25]:
# 2D Array using NumPy
b = np.array([[2,3,4,9],[5,6,9,7]])
print(b)

[[2 3 4 9]
 [5 6 9 7]]


In [19]:
# Get Dimensions
b.ndim

2

In [26]:
# Get Shape of array
b.shape

(2, 4)

In [22]:
# Get Datatype
b.dtype

dtype('int64')

In [30]:
# We can also specify datatype while creating array
c = np.array([7,9,2,5],dtype = 'int16')
print(c)

[7 9 2 5]


In [31]:
c.dtype

dtype('int16')

In [34]:
# size in bytes
c.itemsize

2

In [45]:
# size of elements
c.size

4

In [42]:
# total size
c.size*c.itemsize

8

In [44]:
# total size
c.nbytes

8

### Accessing or changing elements in row, columns


In [48]:
a = np.array([[2,12,16,18,20,26,32],[30,8,45,17,20,60,62]])
print(a)

[[ 2 12 16 18 20 26 32]
 [30  8 45 17 20 60 62]]


In [56]:
# Get specific element [R, C]
print(a[1,5])

60


In [57]:
# get specific row
print(a[0,:])

[ 2 12 16 18 20 26 32]


In [58]:
# get specific column
print(a[:,4])

[20 20]


In [68]:
# Getting a part [start:end:stepsize]
print(a[0,1:6:2])

[12 18 26]


In [73]:
# changing array
a[1, 5] = 106

In [74]:
print(a)

[[  5   5   5   5   5   5   5]
 [ 30   8  45  17  20 106  62]]


In [75]:
 a[0,:]=5
print(a)

[[  5   5   5   5   5   5   5]
 [ 30   8  45  17  20 106  62]]


In [77]:
# 3D array
d = np.array([[[5,6,7],[2,3,4]],[[8,7,6],[4,3,2]]])
print(d)

[[[5 6 7]
  [2 3 4]]

 [[8 7 6]
  [4 3 2]]]


In [81]:
print(d.ndim)
print(d.shape)
# Shape of 3D--> [layer_index, row_index, column_index]

3
(2, 2, 3)


In [82]:
# Access in 3D
d[0,1,2] # 4

np.int64(4)

In [86]:
print(d[0,:,:])
print(d[:,0,:])
print(d[:,:,2])

[[5 6 7]
 [2 3 4]]
[[5 6 7]
 [8 7 6]]
[[7 4]
 [6 2]]


In [90]:
print(d[0,:,1:3])

[[6 7]
 [3 4]]


In [93]:
# replace
d[0,:,1:3] = [[10, 22],[90, 72]]
print(d)

[[[ 5 10 22]
  [ 2 90 72]]

 [[ 8  7  6]
  [ 4  3  2]]]


##  Different type of array

In [95]:
# All 0's matrix
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [98]:
# All one's matrix
np.ones((2,3), dtype = 'int32')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [99]:
# Any Number
np.full((2,2),12)

array([[12, 12],
       [12, 12]])

In [103]:
# Like array
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [108]:
# Random decimal numbers
np.random.rand(8,2)

array([[0.90756815, 0.40944479],
       [0.97419688, 0.28397172],
       [0.01771366, 0.89415807],
       [0.17463183, 0.30015739],
       [0.97427009, 0.41045724],
       [0.84040728, 0.71087205],
       [0.01690114, 0.37650385],
       [0.38713953, 0.38866548]])

In [112]:
np.random.random_sample(a.shape)

array([[0.09065152, 0.15962878, 0.26712476, 0.69154484, 0.77103611,
        0.32909323, 0.41913251],
       [0.38058213, 0.65581046, 0.48521173, 0.55755336, 0.33397679,
        0.23877164, 0.35805737]])

In [119]:
# random integer values (start, stop)
np.random.randint(72,90)


81

In [122]:
np.random.randint(12,size=(3,2))

array([[ 9, 11],
       [ 6,  6],
       [ 6,  0]], dtype=int32)

In [124]:
# Identity
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [133]:
# repeat array
arr = np.array([[4,5,6]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[4 5 6]
 [4 5 6]
 [4 5 6]]


In [136]:
s = np.array([[1,1,1,1,1],[1,0,0,0,1],[1,0,9,0,1],[1,0,0,0,1],[1,1,1,1,1]])
print(s)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [142]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [145]:
output [1:4,1:4] = z # [1:-1,1:-1]
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## When coping arrays !!!

In [146]:
a = np.array([1,2,3])
b= a
b[1]= 100
print(b)
print(a)

[  1 100   3]
[  1 100   3]


In [147]:
a = np.array([1,2,3])
b= a.copy()
b[1]= 100 
print(b)
print(a)

[  1 100   3]
[1 2 3]


## Arithmetics


In [150]:
a + 2

array([3, 4, 5])

In [151]:
a - 2

array([-1,  0,  1])

In [152]:
a * 2

array([2, 4, 6])

In [153]:
a/2


array([0.5, 1. , 1.5])

In [157]:
b= np.array([4,5,6])
a+b

array([5, 7, 9])

In [158]:
b**a

array([  4,  25, 216])

In [160]:
b**2

array([16, 25, 36])

In [161]:
# sine
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

#### Linear Algebra

In [165]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [170]:
# Find Determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [180]:
# Inverse
np.linalg.inv(c)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [187]:
new = np.random.randint(10, size=(3,3))
print(new)

[[8 3 6]
 [4 2 9]
 [0 3 6]]


In [189]:
# Transpose of Matrix
np.linalg.matrix_transpose(new)

array([[8, 4, 0],
       [3, 2, 3],
       [6, 9, 6]], dtype=int32)

## Statistics

In [193]:
n = np.array([[2,3,4],[5,6,7]])

In [194]:
np.min(n)

np.int64(2)

In [195]:
np.max(n)

np.int64(7)

In [197]:
np.max(n, axis = 1)

array([4, 7])

In [202]:
np.sum(n, axis= 0)

array([ 7,  9, 11])

## reshape

In [217]:
b = np.array([[1,2,3,5],[10,12,13,14]])
b

array([[ 1,  2,  3,  5],
       [10, 12, 13, 14]])

In [221]:
e = b.reshape((2,2,2))

In [222]:
print(e)

[[[ 1  2]
  [ 3  5]]

 [[10 12]
  [13 14]]]


In [223]:
# vertical stack
r = np.array([9,9,9,9])
np.vstack([b,r])

array([[ 1,  2,  3,  5],
       [10, 12, 13, 14],
       [ 9,  9,  9,  9]])

In [224]:
# horizontal stack
h1 = np.ones((2,3))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [225]:
np.hstack((h1,h2,h1))

array([[1., 1., 1., 0., 0., 1., 1., 1.],
       [1., 1., 1., 0., 0., 1., 1., 1.]])